"""add agents table and missing fields

Revision ID: 44e0b585c821
Revises: 27758e1b9a40
Create Date: 2026-06-07 16:47:02.998000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e0b585c821'
down_revision: Union[str, None] = '27758e1b9a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('conversations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('is_active', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('agent_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'agent_name')
    op.drop_column('conversations', 'is_active')
    op.drop_column('conversations', 'description')
    op.drop_table('agents')
    # ### end Alembic commands ###
